module.exports = {
  root: true,
  env: { browser: true, es2020: true },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react-hooks/recommended',
  ],
  ignorePatterns: ['dist'],
  parser: '@typescript-eslint/parser',
  plugins: ['react', 'react-refresh', 'import-quotes'],
  rules: {
    'react-refresh/only-export-components': [
      'warn',
      { allowConstantExport: true },
    ],
    indent: [2, 2, { SwitchCase: 1 }],
    quotes: [2, `backtick`],
    semi: [2, `always`],
    "arrow-body-style": [1, `as-needed`],
    "comma-dangle": [`error`, {
      arrays: `always-multiline`,
      exports: `never`,
      functions: `never`,
      imports: `never`,
      objects: `always-multiline`,
    }],
    "eol-last": [2, `always`] ,
    "import-quotes/import-quotes": [2, `single`],
    "no-console": 1,
    "object-curly-spacing": [2, `always`],
    "prefer-const": 1,
    "quote-props" :[2, `as-needed`],
    "react/jsx-closing-bracket-location": [2, `after-props`],
    "react/jsx-first-prop-new-line": [2, `multiline-multiprop`],
    "react/jsx-indent": [2, 2],
    "react/jsx-indent-props": [2, 2],
    "react/jsx-max-props-per-line": [2, { maximum: { single: 1, multi: 1 } }],
    "react/jsx-sort-props": [2, {
      callbacksLast: true,
      ignoreCase: true,
      locale: `auto`,
      multiline: `ignore`,
      noSortAlphabetically: false,
      reservedFirst: true,
      shorthandFirst: true,
    }],
    "react/jsx-tag-spacing": [2]
  },
}